# Most end with '/'
baseURL: 'https://mrincon.net/'
title: M. Rincón
author: M. Rincón
theme: asteriks
languageCode: en-us
copyright: M. Rincón

params:
  subtitle: Guided by asteriks

markup:
  highlight:
    noClasses: false
    lineNos: false

menu:
  main:
  - name: About
    url: /
    weight: 1
  - name: Posts
    url: posts/
    weight: 2
  - name: Tags
    url: /tags
    weight: 3
  icons:
  - name: rss
    weight: 1
  - name: github
    weight: 2
  - name: mastodon
    weight: 3

taxonomies:
   tag: tags
